export const deviceType = [
  'Arduino Due (native USB port)',
  'Arduino Due (programming port)',
  'Arduino Edge Control',
  'Arduino Giga',
  'Arduino Leonardo',
  'Arduino Mega',
  'Arduino Micro',
  'Arduino Nano',
  'Arduino Opta',
  'Arduino Uno',
  'Arduino Zero (native USB port)',
  'Arduino Zero (programming port)',
  'Blackpill STM32-F411CE (DFU STM32 Bootloader)',
  'Blackpill STM32-F411CE (HID Bootloader 2.2)',
  'Blackpill STM32-F411CE (SWD Programmer)',
  'Blackpill STM32-F411CE (Serial Programmer)',
  'Bluepill STM32-F103CB (DFU STM32 Bootloader)',
  'Bluepill STM32-F103CB (HID Bootloader 2.2)',
  'Bluepill STM32-F103CB (SWD Programmer)',
  'Bluepill STM32-F103CB (Serial Programmer)',
  'CONTROLLINO MAXI',
  'CONTROLLINO MAXI Automation',
  'CONTROLLINO MEGA',
  'CONTROLLINO MINI',
  'ESP32 Generic',
  'ESP32 WROOM',
  'ESP32 WROVER',
  'ESP32-C3',
  'ESP32-DOIT DEVKIT V1',
  'ESP32-S2',
  'ESP32-S3',
  'ESP8266 D1-mini',
  'ESP8266 NodeMCU',
  'FX3U-14M / LE3U-14M',
  'FX3U-14M / WS3U-14Mx',
  'FX3U-24MR / DollaTek',
  'Iruino VEA',
  'Mkr WiFi',
  'Mkr Zero',
  'Nano 33 BLE',
  'Nano 33 IoT',
  'Nano Every',
  'Nano RP2040 Connect',
  'P1AM-100',
  'P1AM-200',
  'Portenta Machine Control H7',
  'Project Jaguar',
  'Raspberry Pico',
  'Raspberry Pico W',
  'EQUENT-ESP32-PI',
  'STM32-F446ZET (NUCLEO)',
]
