export enum ModbusFunctionCode {
  DEBUG_INFO = 0x41,
  DEBUG_SET = 0x42,
  DEBUG_GET = 0x43,
  DEBUG_GET_LIST = 0x44,
  DEBUG_GET_MD5 = 0x45,
  DEBUG_GET_STATUS = 0x46,
  DEBUG_GET_VERSION = 0x47,
  DEBUG_GET_BOARD_ID = 0x48,
  DEBUG_WRITE_LICENSE = 0x49,
  DEBUG_READ_LICENSE = 0x4a,
}

export enum ModbusDebugResponse {
  SUCCESS = 0x7e,
  ERROR_OUT_OF_BOUNDS = 0x81,
  ERROR_OUT_OF_MEMORY = 0x82,
  LIC_EMPTY = 0x83,
  LIC_CORRUPT = 0x84,
}
