/**
 * Deciding WHERE the `openplc-cli` shim goes and WHAT it contains.
 *
 * Pure: every filesystem and environment fact is passed in, so the policy can be
 * tested for all three platforms from any one of them. The IO lives in
 * `install-shim.ts`.
 *
 * The policy exists because the obvious answer — "write to /usr/local/bin" — is
 * wrong on a clean machine. That directory is root-owned on stock macOS and on
 * most Linux distributions, so a first-run install there either fails or has to
 * ask for an admin password at launch. Users decline that, reasonably, and an
 * IDE that demands elevation to install a convenience command has mispriced the
 * convenience.
 *
 * So the order is: a directory that is already on PATH and writable without
 * elevation, then `/usr/local/bin` when it happens to be writable (common on a
 * developer's Mac with Homebrew, where it is also certainly on PATH), then a
 * user directory we create ourselves — reporting that it is not on PATH rather
 * than pretending the install succeeded silently.
 */

/** Marks the file as ours, so an install never clobbers someone else's shim. */
export const SHIM_MARKER = 'generated by OpenPLC Editor'

export type ShimPlatform = 'darwin' | 'linux' | 'win32'

export interface ShimEnvironment {
  platform: ShimPlatform
  /** `$HOME` / `%USERPROFILE%`. */
  home: string
  /** `$PATH` / `%Path%`, raw. */
  pathVariable: string
  /** `%LOCALAPPDATA%`, Windows only. */
  localAppData?: string
}

export interface ShimProbes {
  /** Can we create or replace files in this directory (creating it if absent)? */
  isWritable: (directory: string) => boolean
}

export interface ShimCandidate {
  directory: string
  /** True when the directory already appears in PATH. */
  onPath: boolean
  writable: boolean
}

/** The shim's filename — Windows needs an extension the shell will execute. */
export function shimFileName(platform: ShimPlatform): string {
  return platform === 'win32' ? 'openplc-cli.cmd' : 'openplc-cli'
}

/** PATH separator for the platform, since PATH is parsed here, not spawned. */
export function pathSeparator(platform: ShimPlatform): string {
  return platform === 'win32' ? ';' : ':'
}

/**
 * Is `directory` on PATH? Compared case-insensitively on Windows, and with any
 * trailing separator stripped, because `C:\bin\` and `C:\bin` are the same
 * place and a mismatch here would add a duplicate PATH entry on every launch.
 */
export function isOnPath(directory: string, environment: ShimEnvironment): boolean {
  const normalise = (value: string): string => {
    const trimmed = value.trim().replace(/[/\\]+$/, '')
    return environment.platform === 'win32' ? trimmed.toLowerCase() : trimmed
  }
  const target = normalise(directory)
  if (target.length === 0) return false
  return environment.pathVariable
    .split(pathSeparator(environment.platform))
    .some((entry) => entry.length > 0 && normalise(entry) === target)
}

/**
 * Candidate directories, best first, before writability is known.
 *
 * User-writable locations only. No `/usr/local/bin`, no Program Files: a
 * convenience command is not worth an elevation prompt at first launch, and an
 * install that needs root is one that fails on a locked-down machine and
 * succeeds inconsistently everywhere else.
 */
export function candidateDirectories(environment: ShimEnvironment): string[] {
  if (environment.platform === 'win32') {
    // The convention per-user installers use; `%LOCALAPPDATA%\Programs` needs no
    // elevation, unlike Program Files.
    const base = environment.localAppData ?? `${environment.home}\\AppData\\Local`
    return [`${base}\\Programs\\openplc-cli`]
  }
  // `~/.local/bin` is the XDG convention most modern distributions already put
  // on PATH; `~/bin` is the older one Debian's default profile still adds when
  // it exists, so a user who has that instead is not forced to grow a new
  // directory. Whichever is already on PATH wins in `planShimInstall`.
  return [`${environment.home}/.local/bin`, `${environment.home}/bin`]
}

/**
 * The path a shim should invoke — which is not always the running executable.
 *
 * A Linux AppImage runs from a fresh mount point every launch
 * (`/tmp/.mount_…/…`), so a shim pointing at the running executable is stale by
 * the next run. The AppImage runtime exports the path of the `.AppImage` FILE it
 * booted from as `$APPIMAGE`, and that path IS stable — it is wherever the user
 * keeps the file. The AppImage runtime forwards arguments to the app, so
 * `$APPIMAGE --cli devices` works exactly like the mounted binary would.
 *
 * (This is the same mechanism electron-builder's updater uses to find itself,
 * for the same reason.)
 */
export function resolveShimTarget(
  appBinaryPath: string,
  environment: ShimEnvironment & { appImagePath?: string },
): string {
  if (environment.platform === 'linux' && environment.appImagePath) return environment.appImagePath
  return appBinaryPath
}

export interface ShimPlan {
  directory: string
  fileName: string
  /** Absolute path of the shim to write. */
  shimPath: string
  /** Whether the chosen directory is already on PATH. */
  onPath: boolean
  /**
   * True when the platform lets us put the directory on PATH ourselves.
   * Windows has a per-user PATH we can edit; on POSIX, PATH comes from the
   * user's shell profile, and silently editing someone's `.zshrc` is not
   * something an IDE should do behind their back.
   */
  canUpdatePath: boolean
  candidates: ShimCandidate[]
}

/**
 * Choose where the shim goes. Returns undefined only when nothing is writable,
 * which is a real failure worth reporting rather than papering over.
 */
export function planShimInstall(environment: ShimEnvironment, probes: ShimProbes): ShimPlan | undefined {
  const candidates: ShimCandidate[] = candidateDirectories(environment).map((directory) => ({
    directory,
    onPath: isOnPath(directory, environment),
    writable: probes.isWritable(directory),
  }))

  const writable = candidates.filter((candidate) => candidate.writable)
  if (writable.length === 0) return undefined

  // Prefer a writable directory already on PATH; otherwise the first writable
  // one, and the caller tells the user how to add it.
  const chosen = writable.find((candidate) => candidate.onPath) ?? writable[0]
  const fileName = shimFileName(environment.platform)

  return {
    directory: chosen.directory,
    fileName,
    shimPath: environment.platform === 'win32' ? `${chosen.directory}\\${fileName}` : `${chosen.directory}/${fileName}`,
    onPath: chosen.onPath,
    canUpdatePath: environment.platform === 'win32',
    candidates,
  }
}

/**
 * How the shim invokes the app.
 *
 * `leadingArgs` exists because "the app" is not always one path. A packaged
 * build's `process.execPath` IS the app, so `--cli` alone is the whole
 * instruction. In development Electron is a generic binary handed a script, so
 * the script path has to come first — a shim that omitted it ran plain Electron,
 * which cheerfully answered `--version` with ITS version and looked like it
 * worked.
 */
export interface ShimInvocation {
  command: string
  leadingArgs: string[]
}

/**
 * Chromium switches the shim must pass on Linux.
 *
 * These cannot be set from JavaScript: Chromium reads them while starting up,
 * before the main script runs, so `app.commandLine.appendSwitch` is too late.
 * The shim is a command line, which is exactly what they need to be on.
 *
 *   - `--no-sandbox`: the SUID sandbox helper must be root-owned and mode 4755,
 *     which it is not inside a container — the environment CI runs in. Safe for
 *     this process specifically: it creates no renderer and loads no web
 *     content, so the sandbox has nothing to isolate. The GUI never gets this.
 *   - `--ozone-platform=headless`: Electron initialises Ozone before any window
 *     exists and exits when it finds neither X11 nor Wayland ("Missing X server
 *     or $DISPLAY. The platform failed to initialize."). A CLI that never opens
 *     a window still needs this, and it saves callers wrapping everything in
 *     `xvfb-run`.
 */
export function platformSwitches(platform: ShimPlatform): string[] {
  if (platform !== 'linux') return []
  return ['--no-sandbox', '--ozone-platform=headless', '--disable-gpu']
}

/**
 * The shim itself.
 *
 * `exec` on POSIX so the shim does not linger as a parent process, and signals
 * and the exit code pass straight through — a test harness reads that exit code.
 * `"$@"` (not `$*`) keeps arguments with spaces intact, which matters because
 * project paths routinely contain them.
 */
export function renderShim(invocation: ShimInvocation, platform: ShimPlatform): string {
  const parts = [invocation.command, ...platformSwitches(platform), ...invocation.leadingArgs]
  const quoted = parts.map((part) => quoteForShell(part, platform)).join(' ')
  if (platform === 'win32') {
    return [
      '@echo off',
      `rem openplc-cli — ${SHIM_MARKER}. Regenerated on update; edits will be lost.`,
      `${quoted} %*`,
      '',
    ].join('\r\n')
  }
  return [
    '#!/bin/sh',
    `# openplc-cli — ${SHIM_MARKER}. Regenerated on update; edits will be lost.`,
    `exec ${quoted} "$@"`,
    '',
  ].join('\n')
}

/**
 * May we write over what is already at `shimPath`?
 *
 * Only if we recognise it as ours. Someone else's `openplc-cli` on PATH is not
 * ours to replace, and overwriting it would be the kind of surprise that makes
 * people distrust an installer.
 */
export function mayReplace(existingContent: string | undefined): boolean {
  if (existingContent === undefined) return true
  return existingContent.includes(SHIM_MARKER)
}

/**
 * Why this app's location is too ephemeral to point a shim at.
 *
 * A shim is a path written into a file that outlives the process, so it is only
 * as durable as the path. Three cases where it is not durable at all:
 *
 *   - **macOS, running from a mounted disk image** (`/Volumes/…`). The app has
 *     not been installed yet; the shim would break the moment the image is
 *     ejected, and the user would be left with an `openplc-cli` on PATH that
 *     fails with a confusing "no such file".
 *   - **macOS app translocation** (`…/AppTranslocation/…`). Gatekeeper runs a
 *     quarantined app from a randomised read-only path that changes on every
 *     launch, so even a shim written now would be stale by the next one. This is
 *     what happens when someone runs the app straight out of Downloads, and it
 *     looks like a normal launch — which is exactly why it needs naming.
 *   - **Linux AppImage** (`/tmp/.mount_…`). The image mounts itself at a fresh
 *     temporary path per run.
 *
 * Returns undefined when the location is fine.
 */
export function describeUnstableLocation(appBinaryPath: string, platform: ShimPlatform): string | undefined {
  if (platform === 'win32') return undefined

  if (appBinaryPath.includes('/AppTranslocation/')) {
    return (
      'OpenPLC Editor is running from a temporary, randomised location because macOS has quarantined it ' +
      '(this happens when the app is launched straight from Downloads). Move OpenPLC Editor to your ' +
      'Applications folder and open it from there to install the openplc-cli command.'
    )
  }

  if (platform === 'darwin' && appBinaryPath.startsWith('/Volumes/')) {
    return (
      'OpenPLC Editor is running from a disk image, so the openplc-cli command cannot be installed — it ' +
      'would stop working as soon as the image is ejected. Drag OpenPLC Editor into your Applications ' +
      'folder, then open it from there.'
    )
  }

  if (platform === 'linux' && appBinaryPath.startsWith('/tmp/.mount_')) {
    // Reached only when `$APPIMAGE` was absent — `resolveShimTarget` prefers it,
    // and it is the stable path to the .AppImage file. Missing it means the app
    // is running from an extracted or unpacked image with nothing durable to
    // point at.
    return (
      'OpenPLC Editor is running from a temporary mount and the AppImage file path is not available ' +
      '($APPIMAGE is unset), so the openplc-cli command cannot point at it reliably. Run the .AppImage ' +
      'file directly, or install the .deb / .rpm package.'
    )
  }

  return undefined
}

/** What to tell a user whose chosen directory is not on PATH. */
export function pathHint(plan: ShimPlan, platform: ShimPlatform): string | undefined {
  if (plan.onPath) return undefined
  if (platform === 'win32') {
    return `Added ${plan.directory} to your user PATH. Open a new terminal for it to take effect.`
  }
  return (
    `${plan.directory} is not on your PATH. Add it with:\n` +
    `  echo 'export PATH="${plan.directory}:$PATH"' >> ~/.profile\n` +
    'then open a new terminal.'
  )
}

/**
 * Quote one argument so the shell runs it literally.
 *
 * Double quotes are NOT enough. In POSIX sh a double-quoted string still expands
 * `$`, backticks and `\`, and a Windows `.cmd` still expands `%…%` — so an
 * install path containing any of them would change the command the shim runs.
 * Rare, but the blast radius is "executes something else entirely".
 *
 *   - POSIX: single quotes, which suppress every expansion; a literal `'` is
 *     closed, escaped and reopened (`'\''`).
 *   - Windows: keep double quotes (paths contain spaces) and neutralise `%` by
 *     doubling it, which `cmd` reads as a literal percent.
 */
export function quoteForShell(value: string, platform: ShimPlatform): string {
  if (platform === 'win32') return `"${value.replace(/%/g, '%%')}"`
  return `'${value.replace(/'/g, "'\\''")}'`
}
