/**
 * Tests for the trusted_keys.c generator step.
 *
 * The byte-level pins are load-bearing: the generated translation unit
 * defines the symbols the licensable prebuilt artifact references as
 * extern (`LIC_TRUSTED_KEYS` / `LIC_TRUSTED_KEY_COUNT`), and the
 * runtime-v4 plugin checksum hashes the generated bytes — a formatting
 * drift would force needless device-side rebuilds, and a semantic drift
 * (wrong slot, wrong count) would make the device trust the wrong key.
 * Pure functions, no mocks — this suite runs under jest (editor) and
 * vitest (web) unchanged.
 */

import {
  describeTrustedKeysPackagingFault,
  generateTrustedKeysContent,
  parseTrustedKeysJson,
  resolveTrustedKeysArtifact,
} from '../steps/generate-trusted-keys'

/** 128 hex chars: 64 bytes counting 0x00..0x3f — recognisable in the output. */
const HEX_A = Array.from({ length: 64 }, (_, i) => i.toString(16).padStart(2, '0')).join('')
/** 128 hex chars: 64 bytes of 0xab. */
const HEX_B = 'ab'.repeat(64)

const json = (value: unknown) => JSON.stringify(value)

describe('parseTrustedKeysJson', () => {
  it('accepts the canonical single-key shape', () => {
    const result = parseTrustedKeysJson(json({ keys: [{ keyId: 0, pubKeyRawHex: HEX_A }] }))
    expect(result).toEqual({ ok: true, keys: [{ keyId: 0, pubKeyRawHex: HEX_A }] })
  })

  it('accepts uppercase hex (the generator lowercases on emission)', () => {
    const result = parseTrustedKeysJson(json({ keys: [{ keyId: 0, pubKeyRawHex: HEX_B.toUpperCase() }] }))
    expect(result.ok).toBe(true)
  })

  it('tolerates unknown extra fields on entries (forward compatibility)', () => {
    const result = parseTrustedKeysJson(json({ keys: [{ keyId: 0, pubKeyRawHex: HEX_A, label: 'staging-2026' }] }))
    expect(result).toEqual({ ok: true, keys: [{ keyId: 0, pubKeyRawHex: HEX_A }] })
  })

  it('rejects text that is not JSON', () => {
    const result = parseTrustedKeysJson('not json at all {')
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toContain('not valid JSON')
  })

  it('rejects a top level that is not an object with a keys array', () => {
    for (const bad of [json([1, 2]), json('keys'), json(null), json({ notKeys: [] }), json({ keys: 'nope' })]) {
      const result = parseTrustedKeysJson(bad)
      expect(result.ok).toBe(false)
    }
  })

  it('rejects an empty keys array — a licensable package must trust at least one key', () => {
    const result = parseTrustedKeysJson(json({ keys: [] }))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toContain('at least one signing key')
  })

  it('rejects entries that are not objects', () => {
    const result = parseTrustedKeysJson(json({ keys: ['zzz'] }))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toContain('keys[0]')
  })

  it('rejects a non-integer, negative, fractional or out-of-range keyId', () => {
    for (const badKeyId of ['0', -1, 0.5, 256, null]) {
      const result = parseTrustedKeysJson(json({ keys: [{ keyId: badKeyId, pubKeyRawHex: HEX_A }] }))
      expect(result.ok).toBe(false)
      if (!result.ok) expect(result.reason).toContain('keys[0].keyId')
    }
  })

  it('rejects a duplicated keyId', () => {
    const result = parseTrustedKeysJson(
      json({
        keys: [
          { keyId: 3, pubKeyRawHex: HEX_A },
          { keyId: 3, pubKeyRawHex: HEX_B },
        ],
      }),
    )
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toContain('keyId 3 appears more than once')
  })

  it('rejects a pubKeyRawHex that is missing, short, long, or not hex', () => {
    for (const badHex of [undefined, HEX_A.slice(0, 126), `${HEX_A}00`, `zz${HEX_A.slice(2)}`, 42]) {
      const result = parseTrustedKeysJson(json({ keys: [{ keyId: 0, pubKeyRawHex: badHex }] }))
      expect(result.ok).toBe(false)
      if (!result.ok) expect(result.reason).toContain('keys[0].pubKeyRawHex')
    }
  })

  it('rejects keyId 255: the table length would overflow the uint8_t count', () => {
    const result = parseTrustedKeysJson(json({ keys: [{ keyId: 255, pubKeyRawHex: HEX_A }] }))
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.reason).toContain('LIC_TRUSTED_KEY_COUNT')
  })
})

describe('generateTrustedKeysContent', () => {
  it('emits the canonical single-key translation unit byte-for-byte', () => {
    const content = generateTrustedKeysContent([{ keyId: 0, pubKeyRawHex: HEX_A }])
    // The declarations the prebuilt artifact's extern references resolve
    // against — exact spelling, exact type.
    expect(content).toContain('#include <stdint.h>')
    expect(content).toContain('const uint8_t LIC_TRUSTED_KEYS[][64] = {')
    expect(content).toContain('const uint8_t LIC_TRUSTED_KEY_COUNT = 1;')
    // Byte rows: 8 bytes per line, lowercase, trailing commas.
    expect(content).toContain('    {   /* key_id 0 */')
    expect(content).toContain('        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,')
    expect(content).toContain('        0x38, 0x39, 0x3a, 0x3b, 0x3c, 0x3d, 0x3e, 0x3f,')
    // LF-only, trailing newline (the checksum hashes these bytes).
    expect(content).not.toContain('\r')
    expect(content.endsWith(';\n')).toBe(true)
  })

  it('zero-fills keyId gaps as reserved rows and counts the full table', () => {
    const content = generateTrustedKeysContent([
      { keyId: 0, pubKeyRawHex: HEX_A },
      { keyId: 2, pubKeyRawHex: HEX_B },
    ])
    expect(content).toContain('    {   /* key_id 1: reserved (absent from trusted_keys.json) */')
    expect(content).toContain('        0,')
    expect(content).toContain('    {   /* key_id 2 */')
    expect(content).toContain('        0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab, 0xab,')
    // Count is the table LENGTH (maxKeyId + 1), not the number of keys —
    // the core's bounds check reads it as the number of rows.
    expect(content).toContain('const uint8_t LIC_TRUSTED_KEY_COUNT = 3;')
  })

  it('orders rows by keyId regardless of json order (deterministic bytes)', () => {
    const shuffled = generateTrustedKeysContent([
      { keyId: 1, pubKeyRawHex: HEX_B },
      { keyId: 0, pubKeyRawHex: HEX_A },
    ])
    const sorted = generateTrustedKeysContent([
      { keyId: 0, pubKeyRawHex: HEX_A },
      { keyId: 1, pubKeyRawHex: HEX_B },
    ])
    expect(shuffled).toBe(sorted)
    expect(shuffled.indexOf('/* key_id 0 */')).toBeLessThan(shuffled.indexOf('/* key_id 1 */'))
  })

  it('lowercases uppercase hex input', () => {
    const content = generateTrustedKeysContent([{ keyId: 0, pubKeyRawHex: HEX_B.toUpperCase() }])
    expect(content).toContain('0xab,')
    expect(content).not.toContain('0xAB')
  })
})

describe('resolveTrustedKeysArtifact', () => {
  it('generates nothing for a non-licensable target, even with a json present', () => {
    const artifact = resolveTrustedKeysArtifact({
      isLicensable: false,
      packageLabel: 'com.vendor.plain',
      trustedKeysJson: json({ keys: [{ keyId: 0, pubKeyRawHex: HEX_A }] }),
    })
    expect(artifact).toEqual({ kind: 'not-licensable' })
  })

  it('is a packaging fault when a licensable package has no trusted_keys.json', () => {
    const artifact = resolveTrustedKeysArtifact({
      isLicensable: true,
      packageLabel: 'com.vendor.licensed',
      trustedKeysJson: null,
    })
    expect(artifact.kind).toBe('packaging-fault')
    if (artifact.kind === 'packaging-fault') {
      expect(artifact.message).toContain('com.vendor.licensed')
      expect(artifact.message).toContain('missing from the package root')
      expect(artifact.message).toContain('packaging fault')
    }
  })

  it('is a packaging fault when the json is malformed, carrying the parse reason', () => {
    const artifact = resolveTrustedKeysArtifact({
      isLicensable: true,
      packageLabel: 'com.vendor.licensed',
      trustedKeysJson: json({ keys: [] }),
    })
    expect(artifact.kind).toBe('packaging-fault')
    if (artifact.kind === 'packaging-fault') {
      expect(artifact.message).toContain('com.vendor.licensed')
      expect(artifact.message).toContain('at least one signing key')
    }
  })

  it('generates the unit for a licensable package with a valid json', () => {
    const artifact = resolveTrustedKeysArtifact({
      isLicensable: true,
      packageLabel: 'com.vendor.licensed',
      trustedKeysJson: json({
        keys: [
          { keyId: 0, pubKeyRawHex: HEX_A },
          { keyId: 2, pubKeyRawHex: HEX_B },
        ],
      }),
    })
    expect(artifact.kind).toBe('generated')
    if (artifact.kind === 'generated') {
      expect(artifact.keyCount).toBe(2)
      expect(artifact.tableSize).toBe(3)
      expect(artifact.content).toContain('const uint8_t LIC_TRUSTED_KEY_COUNT = 3;')
    }
  })
})

describe('describeTrustedKeysPackagingFault', () => {
  it('names the package, the reason, and calls it a packaging fault', () => {
    const message = describeTrustedKeysPackagingFault('com.vendor.x', 'some reason')
    expect(message).toContain('"com.vendor.x"')
    expect(message).toContain('some reason')
    expect(message).toContain('packaging fault')
  })
})
