export {ReactComponent as SearchIcon} from './search.svg'
export {ReactComponent as FileAndFolderIcon} from './fileAndFolder.svg'
export {ReactComponent as ArrowTransferIcon} from './arrowTransfer.svg'
export {ReactComponent as ZoomInOutIcon} from './zoomInOut.svg'
export {ReactComponent as PlusIcon} from './plus.svg'
export {ReactComponent as TutorialsIcon} from './tutorials.svg'
export {ReactComponent as OpenIcon} from './open.svg'
export {ReactComponent as QuitIcon} from './quitArrow.svg'