/** Reexport all icons from library folder */
export * from './library/CloseFolder'
export * from './library/File'
export * from './library/OpenFolder'

/** Reexport all icons from project folder */
export * from './project/Array'
export * from './project/Block'
export * from './project/CExt'
export * from './project/Coil'
export * from './project/Contact'
export * from './project/DataType'
export * from './project/Device'
export * from './project/Enum'
export * from './project/FBD'
export * from './project/Function'
export * from './project/FunctionBlock'
export * from './project/GenericDT'
export * from './project/IL'
export * from './project/LD'
export * from './project/Loop'
export * from './project/PLC'
export * from './project/Program'
export * from './project/Resource'
export * from './project/SFC'
export * from './project/ST'
export * from './project/Structure'

/** Reexport all icons from interface folder */
export * from './Fallback'
export * from './interface/Arrow'
export * from './interface/ArrowUp'
export * from './interface/Book'
export * from './interface/Close'
export * from './interface/DarkTheme'
export * from './interface/Debugger'
export * from './interface/Download'
export * from './interface/Exit'
export * from './interface/Folder'
export * from './interface/LightTheme'
export * from './interface/Magnifier'
export * from './interface/Minus'
export * from './interface/Pause'
export * from './interface/Pencil'
export * from './interface/Play'
export * from './interface/Plus'
export * from './interface/Search'
export * from './interface/StickArrow'
export * from './interface/Transfer'
export * from './interface/Video'
export * from './interface/View'
export * from './interface/Zap'
export * from './interface/ZoomInOut'

/** Reexport all icons from flow folder */
export * from './flow/Coil'
export * from './flow/Contact'
export * from './flow/Placeholder'
