/** Reexport all icons from library folder */
export * from './library/CloseFolder'
export * from './library/File'
export * from './library/OpenFolder'

/** Reexport all icons from project folder */
export * from './project/Array'
export * from './project/CExt'
export * from './project/DataType'
export * from './project/Device'
export * from './project/Enum'
export * from './project/FBD'
export * from './project/fbd/Block'
export * from './project/fbd/Connector'
export * from './project/fbd/Continuation'
export * from './project/fbd/VariableIn'
export * from './project/fbd/VariableInOut'
export * from './project/fbd/VariableOut'
export * from './project/Function'
export * from './project/FunctionBlock'
export * from './project/GenericDT'
export * from './project/IL'
export * from './project/ladder/Block'
export * from './project/ladder/Coil'
export * from './project/ladder/Contact'
export * from './project/LD'
export * from './project/Loop'
export * from './project/PLC'
export * from './project/Program'
export * from './project/Python'
export * from './project/Resource'
export * from './project/SFC'
export * from './project/ST'
export * from './project/Structure'

/** Reexport all icons from interface folder */
export * from './Fallback'
export * from './interface/Arrow'
export * from './interface/ArrowUp'
export * from './interface/Book'
export * from './interface/Broom'
export * from './interface/Close'
export * from './interface/Config'
export * from './interface/DarkTheme'
export * from './interface/Debugger'
export * from './interface/DeviceTransfer'
export * from './interface/Download'
export * from './interface/Exit'
export * from './interface/Folder'
export * from './interface/LightTheme'
export * from './interface/Magnifier'
export * from './interface/Minus'
export * from './interface/MoreOptions'
export * from './interface/Path'
export * from './interface/Pause'
export * from './interface/Pencil'
export * from './interface/Play'
export * from './interface/Plus'
export * from './interface/Refresh'
export * from './interface/Search'
export * from './interface/StickArrow'
export * from './interface/Stop'
export * from './interface/Timer'
export * from './interface/Transfer'
export * from './interface/TrashCan'
export * from './interface/Video'
export * from './interface/View'
export * from './interface/Zap'
export * from './interface/ZoomInOut'

/** Reexport all icons from flow folder */
export * from './flow/Coil'
export * from './flow/Contact'
export * from './flow/Placeholder'

/** Reexport all icons from window-controls folder */
export * from './window-controls/Close'
export * from './window-controls/Exit-Maximize'
export * from './window-controls/Maximize'
export * from './window-controls/Minimize'
