/**
 * Canonical debug.c parser - shared between debugger and OPC-UA.
 *
 * This module provides the single source of truth for parsing debug.c files
 * generated by the IEC 61131-3 compiler.
 */

export interface DebugVariableEntry {
  /** Full path in debug.c (e.g., "RES0__INSTANCE0.MOTOR_SPEED") */
  name: string
  /** IEC type enum (e.g., "INT_ENUM", "BOOL_ENUM") */
  type: string
  /** Index in the debug_vars array */
  index: number
}

export interface ParsedDebugData {
  variables: DebugVariableEntry[]
  totalCount: number
}

/**
 * Parse the debug.c file content to extract debug variables.
 *
 * @param content - The raw content of debug.c file
 * @returns Array of parsed debug variable entries
 */
export function parseDebugVariables(content: string): DebugVariableEntry[] {
  const variables: DebugVariableEntry[] = []

  const debugVarsMatch = content.match(/debug_vars\[\]\s*=\s*\{([\s\S]*?)\};/)

  if (!debugVarsMatch) {
    console.warn('Could not find debug_vars[] array in debug.c')
    return []
  }

  const arrayContent = debugVarsMatch[1]
  const entryRegex = /\{\s*&\(([^)]+)\)\s*,\s*(\w+)\s*\}/g

  let match
  let index = 0

  while ((match = entryRegex.exec(arrayContent)) !== null) {
    variables.push({
      name: match[1].trim(),
      type: match[2].trim(),
      index,
    })
    index++
  }

  return variables
}

/**
 * Parse the debug.c file and return both variables and total count.
 *
 * @param content - The raw content of debug.c file
 * @returns Parsed debug data with variables and total count
 */
export function parseDebugFile(content: string): ParsedDebugData {
  const variables = parseDebugVariables(content)

  const varCountMatch = content.match(/#define\s+VAR_COUNT\s+(\d+)/)
  const totalCount = varCountMatch ? parseInt(varCountMatch[1], 10) : variables.length

  return { variables, totalCount }
}
