/**
 * `src/rtos_config.h` for a build that runs in RTOS mode.
 *
 * It replaces the skeleton's `OPENPLC_RTOS 0` stub; everything RTOS mode adds
 * compiles only under `#if OPENPLC_RTOS`. A header of its own, not a line in
 * `defines.h`, because the runtime glue must see the switch and does not
 * include `defines.h`.
 *
 * Byte-identical between openplc-editor and openplc-web.
 */

import type { RtosBackend, RtosDebugOwnerRange, RtosTargetProfile } from '../../../../middleware/shared/utils/rtos'

/** The macro that selects the OS shim backend in `plc_os.cpp`. */
const BACKEND_MACRO: Record<RtosBackend, string> = {
  'freertos-esp32': 'OPENPLC_RTOS_FREERTOS_ESP32',
  'freertos-stm32': 'OPENPLC_RTOS_FREERTOS_STM32',
  'freertos-rp2040': 'OPENPLC_RTOS_FREERTOS_RP2040',
  'freertos-renesas': 'OPENPLC_RTOS_FREERTOS_RENESAS',
  'freertos-samd': 'OPENPLC_RTOS_FREERTOS_SAMD',
  'mbed-rtx': 'OPENPLC_RTOS_MBED_RTX',
  zephyr: 'OPENPLC_RTOS_ZEPHYR',
}

export interface GenerateRtosConfigArgs {
  profile: RtosTargetProfile
  /**
   * One thread per IEC task: the STruC++ runtime is built threaded (globals
   * locked per access, IEC time per thread, each program's located slice) and
   * the debugger locks only the tasks whose variables it touches.
   */
  threaded: boolean
  /** The IEC task workers the firmware runs: one per task when threaded, else one. */
  workers: number
  /** Which task owns each run of the debug table; used only when threaded. */
  debugOwners: readonly RtosDebugOwnerRange[]
}

function cString(text: string): string {
  return `"${text.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

export function generateRtosConfigContent({ profile, threaded, workers, debugOwners }: GenerateRtosConfigArgs): string {
  const lines = [
    '// rtos_config.h — generated by the editor: this build runs in RTOS mode.',
    '//',
    '// Replaces the skeleton stub (OPENPLC_RTOS 0). See plc_rtos.h for the task',
    '// model and the tunables that may be defined here.',
    '',
    '#ifndef RTOS_CONFIG_H',
    '#define RTOS_CONFIG_H',
    '',
    '#define OPENPLC_RTOS 1',
    `#define ${BACKEND_MACRO[profile.backend]} 1`,
    `#define OPENPLC_RTOS_TICK_NS ${profile.tickNs}UL`,
    '',
    '// The worker tables are sized to this build.',
    `#define OPENPLC_RTOS_MAX_WORKERS ${Math.min(Math.max(workers, 1), 32)}`,
  ]

  if (threaded) {
    lines.push(
      '',
      '// One thread per IEC task. Seen by every file that includes the STruC++',
      '// runtime (the bundled iec_global.hpp and iec_std_lib.hpp include this',
      '// header first), so they all agree on the layout it changes.',
      '#ifndef STRUCPP_THREADED',
      '#define STRUCPP_THREADED 1',
      '#endif',
    )
    if (profile.threads === 'platform') {
      lines.push(
        '',
        '// No <mutex> or thread_local on this toolchain: the runtime takes its',
        '// locks and IEC time from the RTOS (plc_os.cpp, the runtime glue).',
        '#ifndef STRUCPP_PLATFORM_THREADS',
        '#define STRUCPP_PLATFORM_THREADS 1',
        '#endif',
      )
    }
    if (debugOwners.length > 0) {
      lines.push('', '// Which task owns each run of the debug table: { array, first, last, task }.')
      lines.push('#define OPENPLC_RTOS_DEBUG_OWNERS { \\')
      for (const owner of debugOwners) {
        lines.push(`    { ${owner.arr}, ${owner.first}, ${owner.last}, ${cString(owner.task)} }, \\`)
      }
      lines.push('}')
    }
  }

  lines.push('', '#endif // RTOS_CONFIG_H', '')
  return lines.join('\n')
}

/**
 * The STruC++ runtime headers whose layout `STRUCPP_THREADED` changes. A
 * threaded build makes each of them include `rtos_config.h` first, so no file
 * that includes the runtime can see a different layout from another.
 */
export const THREADED_RUNTIME_HEADERS = ['src/iec_global.hpp', 'src/iec_std_lib.hpp'] as const

/** The sketch sources only RTOS mode compiles; a single-loop build leaves them out. */
export const RTOS_SKETCH_SOURCES = ['examples/Baremetal/plc_os.cpp', 'examples/Baremetal/plc_rtos.cpp'] as const

/** The hooks a runtime built for STRUCPP_PLATFORM_THREADS calls, as declared (not mentioned in a comment). */
const PLATFORM_MUTEX_HOOK = /^\s*extern\s+"C"\s+void\s*\*\s*strucpp_platform_mutex_create\s*\(/m
const PLATFORM_TIME_HOOK = /^\s*extern\s+"C"\s+int64_t\s*\*\s*strucpp_platform_current_time_slot\s*\(/m

/**
 * The bundled STruC++ runtime can take its locks and IEC time from the RTOS
 * (STRUCPP_PLATFORM_THREADS), which a `platform` backend needs to give each IEC
 * task a thread: both headers declare the hooks. The skeleton carries the
 * runtime headers at `src/`.
 */
export function runtimeHasPlatformThreads(firmwareSkeleton: Readonly<Record<string, string>>): boolean {
  return (
    PLATFORM_MUTEX_HOOK.test(firmwareSkeleton['src/iec_global.hpp'] ?? '') &&
    PLATFORM_TIME_HOOK.test(firmwareSkeleton['src/iec_std_lib.hpp'] ?? '')
  )
}

/**
 * The bundled runtime can run each IEC task on a thread of its own on this
 * backend: the headers a threaded build patches are there, and a `platform`
 * backend's runtime has the hooks. Otherwise every task runs on one PLC thread.
 */
export function runtimeCanBeThreaded(
  firmwareSkeleton: Readonly<Record<string, string>>,
  profile: Pick<RtosTargetProfile, 'threads'>,
): boolean {
  if (!THREADED_RUNTIME_HEADERS.every((header) => typeof firmwareSkeleton[header] === 'string')) return false
  return profile.threads === 'native' || runtimeHasPlatformThreads(firmwareSkeleton)
}

export function withRtosConfigInclude(header: string): string {
  return `#include "rtos_config.h"  // RTOS mode: STRUCPP_THREADED, before anything reads it\n${header}`
}
