/**
 * Emit `src/io_sizes.h`, the generated override for the firmware's `MAX_*`
 * I/O buffer sizes.
 *
 * `resources/sources/arduino/openplc.h` picks one of two size sets per MCU
 * family and, until now, that was the end of it: a P1AM-200 with 256 KB of SRAM
 * served the same 56 coils as an Uno with 2 KB, because the number was a
 * literal in a header. That is DOPE-370.
 *
 * Every `MAX_*` in that header is now `#ifndef`-guarded and the header includes
 * this file when it exists, so what is emitted here wins.
 *
 * Two rules make this safe to ship:
 *
 *  - **Growth only.** A count may be raised above the board's firmware default
 *    and never lowered below it. These macros do not only size the Modbus
 *    banks; they dimension the IEC pointer arrays, and `mapEmptyBuffers()`
 *    aliases `%MW`/`%MD`/`%ML` straight into those banks. Shrinking a segment
 *    below what a compiled program addresses would drop I/O silently, with no
 *    diagnostic anywhere. Growing cannot orphan anything.
 *  - **Nothing to say, nothing emitted.** When every requested count equals the
 *    board default, this returns `null` and no file is written, so a project
 *    that never touched the setting compiles byte-for-byte as it did.
 *
 * Pure function — no I/O, no electron, no store.
 */

/** The seven firmware buffer sizes, named as the manifest names them. */
export interface IoSizes {
  digitalInput: number
  digitalOutput: number
  analogInput: number
  analogOutput: number
  memoryWord: number
  memoryDword: number
  memoryLword: number
}

/** Macro each field overrides, in the order `openplc.h` declares them. */
const MACRO_BY_FIELD: Array<[keyof IoSizes, string]> = [
  ['digitalInput', 'MAX_DIGITAL_INPUT'],
  ['digitalOutput', 'MAX_DIGITAL_OUTPUT'],
  ['analogInput', 'MAX_ANALOG_INPUT'],
  ['analogOutput', 'MAX_ANALOG_OUTPUT'],
  ['memoryWord', 'MAX_MEMORY_WORD'],
  ['memoryDword', 'MAX_MEMORY_DWORD'],
  ['memoryLword', 'MAX_MEMORY_LWORD'],
]

/**
 * A Modbus address is 16 bits, so a count above this could not be reached on
 * the wire even if the board had room for it. The register-store fields are
 * `uint16_t` for the same reason.
 */
export const MAX_IO_SIZE = 65535

/**
 * Clamp a requested size set against the board's defaults and ceilings.
 *
 * Returns the sizes that will actually be compiled. Each field is at least the
 * board default (growth only, see the module comment) and at most the board's
 * declared ceiling — or the default itself when the board declares none, which
 * is the conservative reading of "this package has not said how much room the
 * board has".
 */
export function clampIoSizes(
  requested: Partial<IoSizes> | undefined,
  defaults: IoSizes,
  ceilings?: Partial<IoSizes>,
): IoSizes {
  const out = { ...defaults }
  if (!requested) return out

  for (const [field] of MACRO_BY_FIELD) {
    const want = requested[field]
    if (typeof want !== 'number' || !Number.isFinite(want)) continue
    const ceiling = Math.min(ceilings?.[field] ?? defaults[field], MAX_IO_SIZE)
    out[field] = Math.min(Math.max(Math.trunc(want), defaults[field]), ceiling)
  }
  return out
}

/**
 * Build `io_sizes.h`, or `null` when the effective sizes are the board's
 * defaults and there is nothing to override.
 *
 * The output carries an include guard of its own. `defines.h` deliberately has
 * none — it must reach a translation unit through exactly one path — but this
 * file is included from `openplc.h`, which ~20 HAL translation units pull in,
 * so it has to tolerate being seen many times.
 */
export function generateIoSizesHeader(sizes: IoSizes, defaults: IoSizes): string | null {
  const overrides = MACRO_BY_FIELD.filter(([field]) => sizes[field] !== defaults[field])
  if (overrides.length === 0) return null

  const lines = [
    '// Generated by the OpenPLC Editor. Do not edit.',
    '//',
    '// Overrides the per-MCU-family I/O buffer sizes in openplc.h, which are',
    '// `#ifndef`-guarded so this file wins. Only sizes the project raised above',
    '// the board default appear here.',
    '//',
    '// These macros dimension the IEC pointer arrays as well as the Modbus',
    '// banks, and mapEmptyBuffers() aliases %MW/%MD/%ML into those banks -- so',
    '// they are generated as a set and never lowered below the board default.',
    '#ifndef OPENPLC_IO_SIZES_H',
    '#define OPENPLC_IO_SIZES_H',
    '',
  ]
  for (const [field, macro] of overrides) {
    lines.push(`#define ${macro} ${sizes[field]}`)
  }
  lines.push('', '#endif')
  return lines.join('\n') + '\n'
}
