name: Code quality

run-name: OpenPLC CI pipeline - Code quality

on:
  push:
    branches:
      - main
      - development
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - main
      - development
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
