name: Jest test suite CI

run-name: OpenPLC CI pipeline - Step 1 / Unit tests

on: [ push ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm test
