name: Jest test suite CI
run-name: OpenPLC CI pipeline - Step 1/Version 0.0.1
on: [push]
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 24
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js ${{ matrix.node-version }}
          - uses: actions/setup-node@v3
            with:
              node-version: ${{ matrix.node-version }}
          - run: npm ci
          - run: npm test
